version: "3"
services:
  workspace:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
  # backend:
  #   build: ./backend
  #   ports:
  #     - "5000:5000"
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
